language: python
dist: trusty
env:
  - CI_TARGET=vim GOPATH=$HOME/go
  - CI_TARGET=neovim GOPATH=$HOME/go
python:
  - 3.6
install:
  - '[ $CI_TARGET = neovim ] && pip install neovim'
  - pip install vint
  - |
    [ $CI_TARGET = vim ] &&
    sudo add-apt-repository -y ppa:jonathonf/vim &&
    sudo apt-get -y update &&
    sudo apt-get install -y vim-nox
  - |
    [ $CI_TARGET = neovim ] &&
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
script:
  - find config lib -name '*.vim' | xargs vint -c vimrc
  - ln -s $PWD $HOME/.vim
  - mkdir -p $HOME/bin
  - ./bin/install
matrix:
  fast_finish: true
