language: generic
env:
  - CI_TARGET=vim GOPATH=$HOME/go
  - CI_TARGET=neovim GOPATH=$HOME/go
before_script:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - sudo apt-get update
  - sudo apt-get install python3-dev
  - if [ $CI_TARGET = vim ]; then
      sudo add-apt-repository -y ppa:fcwu-tw/ppa &&
      sudo apt-get -qq update &&
      sudo apt-get install -qq vim;
    elif [ $CI_TARGET = neovim ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" &&
      pip3 install neovim;
    fi
script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v vimrc *.vim config lib
  - ln -s $PWD $HOME/.vim
  - mkdir $HOME/bin
  - BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - git fetch origin master:master
  - git checkout master^
  - ./bin/install
  - git checkout $BRANCH
  - $HOME/bin/vim-update
matrix:
  fast_finish: true
