language: generic
env:
  matrix:
    - CI_TARGET=vim
    - CI_TARGET=neovim
before_script:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - sudo apt-get update
  - sudo apt-get install python3-dev
  - if [ $CI_TARGET = vim ]; then
      sudo apt-get install vim-gnome &&
      export DISPLAY=:99.0 &&
      sh -e /etc/init.d/xvfb start;
    elif [ $CI_TARGET = neovim ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" &&
      wget https://bootstrap.pypa.io/get-pip.py &&
      sudo python3 get-pip.py --allow-external sudo &&
      sudo pip3 install neovim;
    fi
env:
  GOPATH=$HOME/go
script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v vimrc *.vim config lib
  - ln -s $PWD $HOME/.vim
  - mkdir $HOME/bin
  - BRANCH=$(git rev-parse --abbrev-ref HEAD)
  - git fetch origin master:master
  - git checkout master^
  - ./bin/install
  - git checkout $BRANCH
  - $HOME/bin/vim-update
