before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - sudo apt-get update && sudo apt-get install -y git mercurial golang vim-gtk

before_script:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v vimrc *.vim config lib
  - mv $PWD $HOME/.vim
  - cd $HOME/.vim
  - ./install
  - cd tests
  - bundle install
  - bundle exec rake
