language: ruby
dist: trusty
env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH

addons: { apt: { packages: [python3-dev] } }

matrix:
  include:
    - env: ENV=neovim
    - env: ENV=vim8

install: |
  pyenv global 3.6
  mkdir -p ${DEPS}/bin
  pip3 install vim-vint

  if [ "$ENV" == "vim8" ]; then
    sudo add-apt-repository -y ppa:jonathonf/vim
    sudo apt-get -y update
    sudo apt-get install -y vim-nox
  elif [ "$ENV" == "neovim" ]; then
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" ||
    pip3 install neovim
    ln -s $(which nvim) ${DEPS}/bin/vim
  fi

script: scripts/test
