language: python
dist: trusty
env:
  - CI_TARGET=vim GOPATH=$HOME/go
  - CI_TARGET=neovim GOPATH=$HOME/go
python:
  - 3.6
before_script:
  - if [ $CI_TARGET = vim ]; then
      sudo add-apt-repository -y ppa:jonathonf/vim &&
      sudo apt-get -y update &&
      sudo apt-get install -y vim-nox;
    elif [ $CI_TARGET = neovim ]; then
      eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" &&
      pip install neovim;
    fi;
    pip install vint
script:
  - which nvim && alias $(which nvim) vim
  - find config lib -name '*.vim' | xargs vint -c vimrc
  - vim --version
  - ln -s $PWD $HOME/.vim
  - mkdir -p $HOME/bin
  - ./bin/install
matrix:
  fast_finish: true
