language: ruby
dist: trusty
env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH
env:
  - CI_TARGET=vim GOPATH=$HOME/go
  - CI_TARGET=neovim GOPATH=$HOME/go

addons:
  apt:
    packages:
    - python3-dev

matrix:
  include:
    - env: ENV=neovim
    - env: ENV=vim8

install: |
  mkdir -p ${DEPS}/bin
  pip install vim-vint

  if [ "$ENV" == "vim8" ]; then
    sudo add-apt-repository -y ppa:jonathonf/vim
    sudo apt-get -y update
    sudo apt-get install -y vim-nox
  elif [ "$ENV" == "neovim" ]; then
    eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64" ||
    pip install neovim
    ln -s $(which nvim) ${DEPS}/bin/vim
  fi

script: scripts/test
